# Generated by Django 4.1.2 on 2023-01-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="salary",
            field=models.FloatField(default=20000),
        ),
    ]
