# Generated by Django 4.1.2 on 2023-01-11 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="logtime",
            old_name="hour_from",
            new_name="date",
        ),
        migrations.RemoveField(
            model_name="logtime",
            name="hour_to",
        ),
        migrations.AddField(
            model_name="logtime",
            name="hour",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
