# Generated by Django 4.1.2 on 2023-01-18 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0003_alter_logtime_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logtime",
            name="hour",
        ),
        migrations.AddField(
            model_name="logtime",
            name="from_hour",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="logtime",
            name="to_hour",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
