# Generated by Django 4.1.2 on 2023-01-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0004_remove_logtime_hour_logtime_from_hour_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="logtime",
            name="hour",
            field=models.FloatField(default=8),
            preserve_default=False,
        ),
    ]
