# Generated by Django 4.1.2 on 2023-01-20 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0005_logtime_hour"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("contact", models.CharField(max_length=15)),
                ("salary", models.FloatField(default=22000)),
                (
                    "avatar",
                    models.ImageField(default="default.jpg", upload_to="employee"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="logtime",
            name="user",
        ),
        migrations.AddField(
            model_name="logtime",
            name="employee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tracking.employee",
            ),
        ),
    ]
