# Generated by Django 4.1.2 on 2023-03-07 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_alter_employee_avatar_alter_employee_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtime',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tracking.employee'),
        ),
    ]
